### PR TITLE
Fixed Scroll Error Footer.js

### LINKED ISSUE #41: fix NavBar Button Error!
After pressing the button its not scrolling to the particular content/ page

### PR DESCRIPTION
**Pull request by bhubesh757**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.
#41 Now , If we click the button , It Scrolls to the Particular Content  
Fixed # (issue) (e.g. Fixed #8)
Fixed issue #41 

## Type of change
Just added  id , ex id = 'contact' to the particular page
Just Added Faq , for example

Please check options that are relevant to your PR.

- [ ✅] Bug fix (non-breaking change which fixes an issue) 
- [ ✅] New feature (non-breaking change which adds functionality)
- [ ❎] This change requires a documentation update

Video:
vokoscreenNG-2021-03-10_16-33-47
Screenshot at 2021-03-10 16-38-50

can i add This ?? FAQ

# Checklist:

- [✅ ] I have squashed my commits
- [ ✅] My code follows the style guidelines of this project
- [✅ ] I have performed a self-review of my own code
- [✅ ] I have commented my code, particularly in hard-to-understand areas
- [ ✅] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by abdus** [comment]
@bhubesh757 issue #41 was not assigned to you. It is assigned to @vismitap. Either pick up a different issue to work on, or ask @vismitap if they would release the issue for you. 

Furthermore, please don't make Pull Requests for issues that were not assigned to you. I will **not** be merging this pull request (unless the issue is released by @vismitap for you to claim). Thank you.

**Comment by bhubesh757** [comment]
@abdus  I Raised the Issue yesterday , I had a Exam Today so Unable to reply to your mentioned comment

**Comment by abdus** [comment]
@bhubesh757 look man, I am sorry. by the time you have responded, I already assigned it to someone else. Please check if @vismitap is okay with this PR. If so, I will go ahead and merge.

I know it feels when we are in situations like this. But please understand that we all have to follow some kind of rules.

**Comment by vismitap** [comment]
Hey @bhubesh757! I understand that you had exams and all but whenever you raise a new issue, always remember to include a line that says 'I want to work on this issue as a part of GSSOC'21' so that the maintainers  and other participants know you want to claim it and under which program you want to claim it. If you don't write this, others get confused whether you just wanted to point out a bug or you want to contribute also.

@abdus, I would like to release this issue as maybe @bhubesh757 did not know about the rules and has worked on it already! It's fine I will look for other issues, np. 😊

**Comment by abdus** [comment]
Awesome, @vismitap. 
@bhubesh757 I will review this in a minute.

**Review by abdus — APPROVED** [review]

**Comment by bhubesh757** [comment]
> Hey @bhubesh757! I understand that you had exams and all but whenever you raise a new issue, always remember to include a line that says 'I want to work on this issue as a part of GSSOC'21' so that the maintainers and other participants know you want to claim it and under which program you want to claim it. If you don't write this, others get confused whether you just wanted to point out a bug or you want to contribute also.
> 
> @abdus, I would like to release this issue as maybe @bhubesh757 did not know about the rules and has worked on it already! It's fine I will look for other issues, np.

@vismitap I am Agreed With Your Point , I am Sorry For That , I Raised The issue , After that I didnt Look into the Github  and Mail After Completing the Exam , I just Solved the issue , and i made a pull request , if it hurts you , sorry for that. @abdus But You handled this Problem calmly Thanks for Accepting the PR.

**Pull request merged**
