### PR TITLE
Added navbar in footer for all the pages of Know About 

### LINKED ISSUE #240: Adding navbar options to footer.
### **Feature request**:

When we go to any "KNOW ABOUT" option like internship, Hackathons, Scholarships, etc. there is no option in website that can user to go back to home page of website. Without browser back option, user can't be able to back to home page of website. 

### **Is your feature request related to a problem? Please describe. (optional)**:

There should be option to user that after going to any page user can directly move to other page of website, at least for home page.

### **Describe the solution you'd like**:

I want to add Navbar option in footer of every "KNOW ABOUT" card page. So that after going through it, user can directly move back where they want without backing again and again using browser back.

### **Describe alternatives you've considered**:

Na

### **Describe how this feature will be useful to our readers**:

This will increase the good user experience.

### **Additional context:**
After clicking any card from here the requirement of this issue comes.
image

<hr/>

**Note:**

- If you want to work on an issue, you should check if it has already been assigned to anyone.

### PR DESCRIPTION
**Pull request by RuchiGitHu**
# Description

I have added Navbar option in footer of every "KNOW ABOUT" card page. So that after going through it, user can directly move back where they want without backing again and again using browser back.
image
image

Fixed #240  (issue) (e.g. Fixed #8)

## Type of change

Please check options that are relevant to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have pulled the latest changes in the repository
- [ ] I have squashed my commits
- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by RuchiGitHu** [comment]
> # Description
> I have added Navbar option in footer of every "KNOW ABOUT" card page. So that after going through it, user can directly move back where they want without backing again and again using browser back.
> image
> image
> 
> Fixed #240 (issue) (e.g. Fixed #8)
> 
> ## Type of change
> Please check options that are relevant to your PR.
> 
> * [ ]  Bug fix (non-breaking change which fixes an issue)
> * [x]  New feature (non-breaking change which adds functionality)
> * [ ]  This change requires a documentation update
> 
> # Checklist:
> * [x]  I have pulled the latest changes in the repository
> * [ ]  I have squashed my commits
> * [x]  My code follows the style guidelines of this project
> * [ ]  I have performed a self-review of my own code
> * [ ]  I have commented my code, particularly in hard-to-understand areas
> * [ ]  I have made corresponding changes to the documentation
> * [x]  My changes generate no new warnings

Please review @Manvityagi

**Comment by Manvityagi** [comment]
@DeepanshiD 
@vaishali614

**Comment by RuchiGitHu** [comment]
> @DeepanshiD
> @vaishali614

Kindly review my PR @Manvityagi

**Comment by vaishali614** [comment]
@RuchiGitHu That doesn't really look good to me. Footers aren't usually this much crowded. I think the purpose of navigating to homepage is served by the logo in header. 
If you still feel the need, then we'll probably need to change the design of the footer. @DeepanshiD can probably help with that.
CC: @Manvityagi

**Comment by RuchiGitHu** [comment]
> @RuchiGitHu That doesn't really look good to me. Footers aren't usually this much crowded. I think the purpose of navigating to homepage is served by the logo in header.
> If you still feel the need, then we'll probably need to change the design of the footer. @DeepanshiD can probably help with that.
> CC: @Manvityagi

First of all thanks for your important review. Secondly, I think less people are aware or would have idea that after clicking in logo they can go back to home page. I will change my way of solving this issue and this time it will not too crowded in footer in fact I were thinking to resolve this other approach (I can add only Home button in navbar, this will not effect footer and the home button in navbar will let user go to home). Your suggestions are welcome as always.
Looking forward for your reply @Manvityagi @DeepanshiD @vaishali614

**Comment by vaishali614** [comment]
> > @RuchiGitHu That doesn't really look good to me. Footers aren't usually this much crowded. I think the purpose of navigating to homepage is served by the logo in header.
> > If you still feel the need, then we'll probably need to change the design of the footer. @DeepanshiD can probably help with that.
> > CC: @Manvityagi
> 
> First of all thanks for your important review. Secondly, I think less people are aware or would have idea that after clicking in logo they can go back to home page. I will change my way of solving this issue and this time it will not too crowded in footer in fact I were thinking to resolve this other approach (I can add only Home button in navbar, this will not effect footer and the home button in navbar will let user go to home). Your suggestions are welcome as always.
> Looking forward for your reply @Manvityagi @DeepanshiD @vaishali614

I agree with you that people are less aware about logo on navbar can take them to homepage. However, we do have a Products section in footer where Opportunity Calendar takes us to the homepage. I'm not really sure if adding a Home button or simply a link in navbar would look good. 
I think @DeepanshiD can help us better with this decision.
CC: @Manvityagi

**Comment by DeepanshiD** [comment]
@RuchiGitHu  We have a sticky header and we are adding same contents of header in footer, which isn't a nice decision anyway. I don't think there's a need of footer navigation 
CC: @vaishali614 @Manvityagi

**Comment by Manvityagi** [comment]
> @RuchiGitHu We have a sticky header and we are adding same contents of header in footer, which isn't a nice decision anyway. I don't think there's a need of footer navigation
> CC: @vaishali614 @Manvityagi

Hmm, That's apt @DeepanshiD. Okay, let's keep it this way, Sorry @RuchiGitHu will have to close this one. Thanks for the efforts that you have made.

**Pull request closed without merging**
