### PR TITLE
Update autoLabel.yaml

### LINKED ISSUE #232: small update in  autoLabel.yaml
### **Describe the bug:**

file not giving the required result

### PR DESCRIPTION
**Pull request by Inventor77**
# Description

small update in file

Fixed #232

### CODE REVIEW

**Comment by Manvityagi** [comment]
> # Description
> small update in file

Is there an issue linked to this PR?

**Comment by Inventor77** [comment]
> > # Description
> > small update in file
> 
> Is there an issue linked to this PR?

No mam, Should I make one

**Comment by Inventor77** [comment]
@Manvityagi ?

**Comment by Manvityagi** [comment]
> > > # Description
> > > small update in file
> > 
> > 
> > Is there an issue linked to this PR?
> 
> No mam, Should I make one

Yes please

**Comment by vaishali614** [comment]
@Inventor77 Have you created an issue for this? If yes, please mention that along with your description. Also, your branch is 14 commits behind the upstream, please take the latest pull.

**Comment by Inventor77** [comment]
> @Inventor77 Have you created an issue for this? If yes, please mention that along with your description. Also, your branch is 14 commits behind the upstream, please take the latest pull.

@vaishali614  Yes mam I have created Issue for it please lend me some time I will Update the PR

**Review by Manvityagi — APPROVED** [review]

**Pull request merged**
