### PR TITLE
Fixed UI gitch and clean up the code

### LINKED ISSUE #221: Inappropriate alignment of cards in tablet mode (768x1024)
# Expected Behavior:

Cards appear to be on the center rather than the left.

# Current Behavior:

What is the current behavior?
Cards appear to be on the left side rather than the center.

# Solution:
Will align the cards to the center in tablet mode.

# Screenshots (optional):
image_2021_04_19T08_42_58_366Z

### PR DESCRIPTION
**Pull request by Samridhi-98**
# Description

Fixed UI gitch and clean up the code

Fixed #221 

## Type of change

- [x] Fixed alignment in iPad and other modes. 
- [x] Clean up the code(Removed unnecessary warnings) 

Please check options that are relevant to your PR.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have pulled the latest changes in the repository
- [x] I have squashed my commits
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# Screenshot
image_2021_04_19T15_42_00_915Z

### CODE REVIEW

**Comment by Samridhi-98** [comment]
@vaishali614 will you please review my PR.

**Review by Manvityagi — CHANGES_REQUESTED** [review]
Clean up code part looks good, but the cards still are not at the center for many view-ports 
image

**Comment by Samridhi-98** [comment]
> Clean up code part looks good, but the cards still are not at the center for many view-ports
> image

Will improve it.

**Comment by Samridhi-98** [comment]
@Manvityagi Done! Please check

**Comment by Manvityagi** [comment]
> @Manvityagi Done! Please check

It has improved a lot as compared to the last PR, 
but there are still some problems with some screen sizes,

See the gif attached 
[](https://gifyu.com/image/tQgH)

**Comment by Samridhi-98** [comment]
@Manvityagi  Please check, I have updated all viewports and also removed unnecessary media queries.

**Review by Manvityagi — APPROVED** [review]
Looks awesome!!

**Pull request merged**
