### PR TITLE
Added all push forks in readme file

### LINKED ISSUE #118: To Add No of issues/pullrequests/forks/watchers/stars in Readme file
@abdus can i work on this?

### PR DESCRIPTION
**Pull request by saumyasrivastava08**
#118 
@Manvityagi

### CODE REVIEW

**Review by Manvityagi — CHANGES_REQUESTED** [review]
Let this PR do only what it intends to do, 
For Changing the functional component to class component, you can raise a separate issue.

**Review by Manvityagi — CHANGES_REQUESTED** [review]
Also mention what changes have been done in the PR description.

**Comment by saumyasrivastava08** [comment]
@Manvityagi okay

**Comment by saumyasrivastava08** [comment]
I have added number of issues  , or, forks, watchers ,stars in readme file which will looks good.
Screenshot (65)

**Comment by saumyasrivastava08** [comment]
@Manvityagi done and attached ss also

**Comment by vaishali614** [comment]
@saumyasrivastava08 Looks good to me.
cc: @Manvityagi

**Comment by Manvityagi** [comment]
> @Manvityagi done and attached ss also

The content looks good, 
Can you move this to Just before Table of Contents? 

It will make more sense at the beginning.

**Comment by saumyasrivastava08** [comment]
okay sure

**Review by Manvityagi — APPROVED** [review]
Looks good to me 😃

Cc: @Surajbokde

**Review by Surajbokde — APPROVED** [review]

**Pull request merged**
