### PR TITLE
fixes #198

### LINKED ISSUE #198: Update footer
1. Redirect CodeMaps to: "https://girlcodeit.com/codemaps"
2. Redirect Opportunity Calendar to: "/" i.e. the homepage itself
3. Convert headings (PRODUCT, LINKS and CONTACT US) to normal case (Products, Links, Contact Us)
4. Underline Contact Us too
5. Redirect logo to: https://girlcodeit.com/
6. Align copyright icon with '2021 Girl Code It'

### PR DESCRIPTION
**Pull request by wajeehamushtaq**
fixes #198. I have fix these issues if there are other issues of level 2 and 3 please assign them to me as well

### CODE REVIEW

**Comment by vaishali614** [comment]
1. Add cursor : pointer on hovering CodeMaps and Opportunity Calendar
2. Remove underline from the logo on hover and shift it to center like it was before
3. Add some space between Contact Us and the line below as in Products and Links

**Comment by wajeehamushtaq** [comment]
@vaishali614 done. I have fixes issues

**Comment by vaishali614** [comment]
> @vaishali614 done. I have fixes issues

Point 1 is still not added and please take the latest pull from upstream before updating your PR.

**Comment by wajeehamushtaq** [comment]
@vaishali614 Can you please explain Point 1 as I have added the cursor on the hover in the "Products" and "Links" section in the footer.

**Comment by vaishali614** [comment]
> @vaishali614 Can you please explain Point 1 as I have added the cursor on the hover in the "Products" and "Links" section in the footer.

You need to add cursor on CodeMaps and Opportunity Calendar, not Products and Links.

**Comment by wajeehamushtaq** [comment]
Added cursor : pointer on hovering to CodeMaps and Opportunity Calendar

**Comment by vaishali614** [comment]
It looks distorted in mobile and tab view. Please crosscheck for all the screensizes and update your PR.

1Capture
2Capture

**Review by vaishali614 — CHANGES_REQUESTED** [review]
It looks distorted in mobile and tab view. Please crosscheck for all the screensizes and update your PR.

1Capture
2Capture

**Comment by wajeehamushtaq** [comment]
I have added the requested changes. Please review them. Please add an appropriate level in GSSOC'21 PR label as I have done much work in PR. Thank you.

**Comment by vaishali614** [comment]
> I have added the requested changes. Please review them. Please add an appropriate level in GSSOC'21 PR label as I have done much work in PR. Thank you.
> 
> 
> 

Please check for all the screens. The logo is still not in center for various screens. Also, the underline for Contact Us seems distorted for many screens.

**Comment by wajeehamushtaq** [comment]
Corrected all screens

**Review by vaishali614 — APPROVED** [review]

**Pull request merged**
