### PR TITLE
(feature) - Added Custom Scrollbar

### LINKED ISSUE #171: Scroll Bar
### **Feature request**:

An attractive scroll bar (Blue and White-colored). I would like to add this as a GSSOC'21 participant

### **Describe how this feature will be useful to our readers**:

It will make the webpage look more attractive.

### **Additional context:**

image

<hr/>

**Note:**

- If you want to work on an issue, you should check if it has already been assigned to anyone.

### PR DESCRIPTION
**Pull request by shriya030**
# Description

Added a custom scrollBar of blue and black colour

Fixed #171 

## Type of change

Please check options that are relevant to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have pulled the latest changes in the repository
- [x] I have squashed my commits
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by DeepanshiD** [comment]
@shriya030 Keep it grey without gradient

**Comment by shriya030** [comment]
@DeepanshiD 
image
image

Which one of the two? With light background or without background?

**Comment by DeepanshiD** [comment]
@shriya030 First one has to be kept, keep color of bar C4C4C4 and background EFEFEF

**Comment by shriya030** [comment]
> @shriya030 First one has to be kept, keep color of bar C4C4C4 and background EFEFEF

@DeepanshiD done!

**Comment by DeepanshiD** [comment]
@shriya030 Looks perfect!
CC @vaishali614

**Comment by shriya030** [comment]
> @shriya030 Looks perfect!
> CC @vaishali614

Will this be merged? 
It is closed by you so I thought!

**Comment by vaishali614** [comment]
> > @shriya030 Looks perfect!
> > CC @vaishali614
> 
> Will this be merged?
> It is closed by you so I thought!

Apologies. It was closed by mistake. Changes look good.
Your fork isn't even with upstream. Please pull the latest changes and update your PR.

**Comment by shriya030** [comment]
> > > @shriya030 Looks perfect!
> > > CC @vaishali614
> > 
> > 
> > Will this be merged?
> > It is closed by you so I thought!
> 
> Apologies. It was closed by mistake. Changes look good.
> Your fork isn't even with upstream. Please pull the latest changes and update your PR.

Check now @vaishali614

**Pull request merged**
