### PR TITLE
Sushi22/signuplogin

### LINKED ISSUE #30: Create Signup login Components
image
create something like this.
best one will be selected
Add proper screenshots when it is done

### PR DESCRIPTION
**Pull request by Sushi22**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixed # (issue) (e.g. Fixed #8)

## Type of change

Please check options that are relevant to your PR.

- Bug fix (non-breaking change which fixes an issue)
-  New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- I have squashed my commits
- My code follows the style guidelines of this project
-  I have performed a self-review of my own code
-  I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
-  My changes generate no new warnings

### CODE REVIEW

**Review by abdus — CHANGES_REQUESTED** [review]
- Navigation bar is missing
- Your PR creates some side-effects. Can you fix this, please? [Here's how it should look](https://happy-shockley-488e36.netlify.app/viewopportunity/fulltime).

**Comment by Sushi22** [comment]
> * Navigation bar is missing
> * Your PR creates some side-effects. Can you fix this, please? [Here's how it should look](https://happy-shockley-488e36.netlify.app/viewopportunity/fulltime).
> 
> 



> * Navigation bar is missing
> * Your PR creates some side-effects. Can you fix this, please? [Here's how it should look](https://happy-shockley-488e36.netlify.app/viewopportunity/fulltime).
> 
> 

Ohh!yeah sure I will correct it.

**Comment by Sushi22** [comment]
@abdus  I have corrected the code. Please review

**Comment by Sushi22** [comment]
@abdus I am sorry there is an issue , with that pull request , by mistake two folders have been created for signupLogin, I apologise for my mistake , I request you to please revert this pull request and close it. I am sending another PR which is the final one.

**Comment by abdus** [comment]
I fixed it after merging the PR (somehow forgot to push the changes). anyways, I will go ahead and merge the new PR.

**Pull request merged**
