### PR TITLE
(feature) - Enhanced FAQ section

### LINKED ISSUE #119: Enhancing FAQ Section
### **Feature request**:
I want to add transition in FAQ section (when questions are being opened and closed) and also when one question is opened, the other one should automatically close. Also changing the cursor to pointer when the user hovers over the question.

### **Describe the solution you'd like**:
The changes will be made in CSS file i.e. transition will be applied and React Hooks will be used to add the feature of automatically closing a question, when other question is being opened.

### **Describe how this feature will be useful to our readers**:
This feature will enhance the readability of faqs and also the design of the website.

Please assign me this issue as a part of GSSOC'21.

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

### PR DESCRIPTION
**Pull request by shriya030**
# Description

Added transition to FAQ questions, when the user hovers over any question, the cursor changes to pointer and added the feature i.e when one question is clicked, the other question closes automatically. 

Fixed #119  

## Type of change

Please check options that are relevant to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have squashed my commits
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by Surajbokde — APPROVED** [review]

**Review by Surajbokde — APPROVED** [review]

**Comment by Surajbokde** [comment]
@shriya030  looks good to me .

**Comment by Manvityagi** [comment]
@DeepanshiD Can you suggest something for the FAQ transition? I didn't really like the transition.

**Comment by shriya030** [comment]
> @DeepanshiD Can you suggest something for the FAQ transition? I didn't really like the transition.

Actually, I did something different, when the question is being clicked, the answer is appearing from the left side, and then while closing, it is going away.

**Comment by Surajbokde** [comment]
@shriya030 make transaction from top to bottom ,from top i mean to say answer will come from ,behind the question

**Comment by shriya030** [comment]
> @shriya030 make transaction from top to bottom ,from top i mean to say answer will come from ,behind the question

I am facing a problem in that. Please help me out, I've texted you on discord.

**Comment by shriya030** [comment]
> @DeepanshiD Can you suggest something for the FAQ transition? I didn't really like the transition.

@Manvityagi I hope it's fine now. :) I have made the changes

**Review by Manvityagi — APPROVED** [review]
Looks good to me 😄 

Thanks for the contribution @shriya030.

**Review by vaishali614 — APPROVED** [review]

**Review by Surajbokde — APPROVED** [review]

**Pull request merged**
