### PR TITLE
Modified Post opportunity

### LINKED ISSUE #92: Modify Page of Post Job Opportunity
Screenshot (63)

###Following changes to be made
1.) Box around the form that will look attractive
2.) Shift search bar corner / add login option

### PR DESCRIPTION
**Pull request by saumyasrivastava08**
#92 

@abdus  done

### CODE REVIEW

**Comment by saumyasrivastava08** [comment]
@abdus  why such errors are coming ?

**Comment by abdus** [comment]
@saumyasrivastava08 It looks like the lock-file is dirty. here's how to fix it: 

1. delete `package-lock.json`
2. run `npm install` inside the project directory
3. push

**Comment by saumyasrivastava08** [comment]
@abdus conflict with package-lock.json?

**Comment by abdus** [comment]
again? how that is even possible? can you delete it and regenerate it once again, please? make sure to pull the latest changes first.

**Comment by saumyasrivastava08** [comment]
Done @abdus

**Pull request merged**
