### PR TITLE
Added Validation to Post Opportunities page

### LINKED ISSUE #31: Add validation  in post a job opportunity
image
Add validation in this

### PR DESCRIPTION
**Pull request by AishwaryaKaranth**
I have added validation to all the fields.
- It checks if the job ID, location, title, company, short description, eligibility, and job descriptions fields are empty fields.
- I have used RegEx to check for invalid URLs.
- For deadline field, I have used input type = date.
- If the fields are not valid error messages will be displayed.

reactValidation

Fixed #31

### CODE REVIEW

**Comment by abdus** [comment]
Fix conflicts. @Surajbokde can you please review this PR?

**Comment by DeepanshiD** [comment]
@AishwaryaKaranth 
The design has to be something similar to the image shown below, where the title text is fixed, error message left margin is same as input field left margin
WhatsApp Image 2021-03-14 at 11 02 35

**Comment by AishwaryaKaranth** [comment]
> @AishwaryaKaranth
> The design has to be something similar to the image shown below, where the title text is fixed, error message left margin is same as input field left margin
> WhatsApp Image 2021-03-14 at 11 02 35

Okay, I'll fix it.

**Comment by AishwaryaKaranth** [comment]
added left margin for error messages.  
reactValidation1

**Comment by abdus** [comment]
Please resolve conflicts.

**Comment by AishwaryaKaranth** [comment]
> Please resolve conflicts.

I tried to resolve conflicts in GitHub interface, but commit merge option is not available.
reactvalidation3

**Pull request closed without merging**
