### PR TITLE
Updated files for Post Opportunity Page Revamp

### LINKED ISSUE #165: Post Opportunity Page Revamp
Revamping of Post Opportunity Page:

1. `Find Opportunity` button should redirect to `View Opportunity` page of respective opportunity.
2. Dropdown should have the following values which will redirect to `Post Opportunity` page of those opportunities: 
- JOB
- INTERNSHIP
- HACKATHON
- SCHOLARSHIP
- CODINGCOMPETITION
- CONFERENCE
3. `Find Opportunity` button in navbar should redirect to only that opportunity of which user is posting the opportunity.
4. Must be responsive for all screen sizes.

[Follow this design](https://www.figma.com/proto/XKmx5ia2hGjM9iz3VdWABp/girlcodeit?node-id=602%3A55&scaling=min-zoom&page-id=0%3A1)

### PR DESCRIPTION
**Pull request by AshuKV**
# Description

Dependencies: The `TechConf`, `Hackathons`, and `Scholarships` page needs to be rechecked to get itself redirected when a user clicks on the respective button. 

Fixed #165 

## Type of change

Please check options that are relevant to your PR.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Checklist:

- [x] I have pulled the latest changes in the repository
- [x] I have squashed my commits
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by vaishali614 — CHANGES_REQUESTED** [review]
@AshuKV Have you gone through the design shared in #165 ? You're supposed to replicate the same design.

**Comment by AshuKV** [comment]
> @AshuKV Have you gone through the design shared in #165 ? You're supposed to replicate the same design.

Ok sure, I have started working on this and would commit the updated code with this design soon.

**Comment by vaishali614** [comment]
> > @AshuKV Have you gone through the design shared in #165 ? You're supposed to replicate the same design.
> 
> Ok sure, I have started working on this and would commit the updated code with this design soon.

Any updates?

**Comment by vaishali614** [comment]
> > > @AshuKV Have you gone through the design shared in #165 ? You're supposed to replicate the same design.
> > 
> > 
> > Ok sure, I have started working on this and would commit the updated code with this design soon.
> 
> Any updates?

@AshuKV I expect an update by tomorrow, otherwise I'll have to discard this PR and assign the issue to someone else as per Deadline rules.

**Comment by vaishali614** [comment]
@AshuKV Due to your inactiveness, I'm closing this PR.

**Pull request closed without merging**
