### PR TITLE
feature/icon - added icon-navbar

### LINKED ISSUE #190: Add icon in navbar
### **Feature request**:

We can add 'logo/icon' just before the title 'Girl Code It'.

### **Is your feature request related to a problem? Please describe. (optional)**:

No

### **Describe the solution you'd like**:

Add 'logo' in navbar and also it will be linked to home page.

### **Describe alternatives you've considered**:

N/A

### **Describe how this feature will be useful to our readers**:

Requesting change is 'view/design' of page.

### **Additional context:**

N/A

<hr/>

**Note:**

- If you want to work on an issue, you should check if it has already been assigned to anyone.

### PR DESCRIPTION
**Pull request by Spring-dot**
# Description

Added icon in the navbar.

Fixed #190 

## Type of change

Please check options that are relevant to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have pulled the latest changes in the repository
- [ ] I have squashed my commits
- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by Spring-dot** [comment]
@Manvityagi please review this

**Comment by Manvityagi** [comment]
The icon in navbar is looking a little off to me

Cc: @DeepanshiD

**Comment by vaishali614** [comment]
> The icon in navbar is looking a little off to me
> 
> Cc: @DeepanshiD

yeah, it doesn't look good to me as well.

**Comment by abdus** [comment]
hey @Spring-dot, although you contributed meaningful stuff, the maintainers didn't find it suitable for the time being. So, I am going to close it for now.

**Pull request closed without merging**
