### PR TITLE
Social Icons added

### LINKED ISSUE #242: Add Social Icons to left of website
### **Feature request**:

I want to add social icons to left side of website, which on hovering scales out.

### **Describe the solution you'd like**:

I am a GSSoC'21 participant please assign this issue to me.
I have added this feature to a website and there its screenshot.
image

<hr/>

**Note:**

- If you want to work on an issue, you should check if it has already been assigned to anyone.

### PR DESCRIPTION
**Pull request by ShrutiOmer**
# Description

I have added social icons to left of website
Fixed #242

image

## Type of change

Please check options that are relevant to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have pulled the latest changes in the repository
- [x] I have squashed my commits
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by Manvityagi — CHANGES_REQUESTED** [review]
image
On smaller screens, these are overlapping with text


image
It should be like this

**Comment by ShrutiOmer** [comment]
I have made the changes. @Manvityagi  please review it.
Untitled

**Comment by Manvityagi** [comment]
image
Doesn't this look a bit off on this screen? 
CC: @vaishali614 

Let's have the social media icons only on Home Page?

**Comment by Manvityagi** [comment]
> image
> Doesn't this look a bit off on this screen?
> CC: @vaishali614
> 
> Let's have the social media icons only on Home Page?

@ShrutiOmer

**Comment by vaishali614** [comment]
> image
> Doesn't this look a bit off on this screen?
> CC: @vaishali614
> 
> Let's have the social media icons only on Home Page?

I agree. Let's have it on the homepage only.

**Comment by vaishali614** [comment]
I think there's too much space here, can we reduce it a bit?

Capture

**Comment by ShrutiOmer** [comment]
@Manvityagi  @vaishali614  I have added social icons in the home page, but the space is changing with zoom level.
see this 
image

and with different zoom
image

It is behaving same as in original site.
image

 If I will change left margin from auto to something then it will not come in centre.

**Comment by vaishali614** [comment]
@ShrutiOmer No problem. Looks good this way. Please take the latest pull from upstream and update your PR so that I can merge this PR.

**Comment by ShrutiOmer** [comment]
@vaishali614  I have pull the upstream.

**Review by vaishali614 — APPROVED** [review]

**Comment by rakshaa2000** [comment]
LGTM

**Review by rakshaa2000 — APPROVED** [review]
LGTM

**Comment by ShrutiOmer** [comment]
@vaishali614 @rakshaa2000 @Manvityagi  please add the labels, without labels point will not update in leaderboard.

**Pull request merged**
