### PR TITLE
review

### LINKED ISSUE #32: Design view opportunity component for mobile and tab view
image
image
modify the circled part in both images

### PR DESCRIPTION
**Pull request by saumyasrivastava08**
Fixed issue #32 
Design view opportunity component

### CODE REVIEW

**Comment by saumyasrivastava08** [comment]
@abdus this is to be consider for #32

**Comment by abdus** [comment]
@saumyasrivastava08 From inside the project directory in terminal/Powershell/command prompt, please run the following commands: 

```sh
git rm -rf yarn.lock 
# this will remove yarn.lock file from git tree and file system. 
# we are using `npm` for this project. and having two package 
# managers for a single project usually creates unwanted problems
```
after you are done running the above command, open `.gitignore` and add `yarn.lock` at the end. This will make sure that yarn's lock file does not get committed into git.

Then add, commit and push the changes. 

---

About the failing checks: I have no idea why they are failing on Netlify. Haven't encountered such error on Netlify before. I tried building this PR locally and it finished without an error. This could possibly be happening because of multiple lock files.

Also, add screenshots of your changes (as it's an UI change).

**Comment by saumyasrivastava08** [comment]
Sure @abdus doing the changes and attaching ss also

**Comment by saumyasrivastava08** [comment]
Screenshot (49)
Screenshot (50)
Screenshot (51)

**Comment by saumyasrivastava08** [comment]
@abdus Done with the task and attached screenshots also

**Comment by abdus** [comment]
@saumyasrivastava08 all checks passed!! looks like having multiple lock files was the issue. congrats on solving it. I will ask for reviews from other mentors. Once they approve, I will merge it.

**Comment by Surajbokde** [comment]
@saumyasrivastava08  issue #32  is not resolve yet  .
make use of React-Bootstrap framework to complete this issue

**Comment by saumyasrivastava08** [comment]
> @saumyasrivastava08 issue #32 is not resolve yet .
> make use of React-Bootstrap framework to complete this issue

I did make the use can u explain more brieflyy

**Comment by Surajbokde** [comment]
> > @saumyasrivastava08 issue #32 is not resolve yet .
> > make use of React-Bootstrap framework to complete this issue
> 
> I did make the use can u explain more brieflyy

image
image
image
do this changes

**Comment by saumyasrivastava08** [comment]
> > > @saumyasrivastava08 issue #32 is not resolve yet .
> > > make use of React-Bootstrap framework to complete this issue
> > 
> > 
> > I did make the use can u explain more brieflyy
> 
> image
> image
> image
> do this changes

I will fix it asap

**Comment by vaishali614** [comment]
@saumyasrivastava08 I don't like the design. I think it would look better if you try something similar as below - 

Screenshot (224)

**Comment by saumyasrivastava08** [comment]
> @saumyasrivastava08 I don't like the design. I think it would look better if you try something similar as below -
> 
> Screenshot (224)

I was thinking to change but I was a little bit confused what if I changed the things and you will not accept.

**Comment by saumyasrivastava08** [comment]
@Surajbokde done with the changes.

**Review by Surajbokde — CHANGES_REQUESTED** [review]
this issue is resolve as sub issue.
so you need to pull all the changes and

image
do this change only

**Comment by saumyasrivastava08** [comment]
> this issue is resolve as sub issue.
> so you need to pull all the changes and
> 
> image
> do this change only

I need to add only this feature right

**Comment by saumyasrivastava08** [comment]
@Surajbokde can u check

**Review by Surajbokde — APPROVED** [review]

**Comment by Surajbokde** [comment]
@vaishali614  please check

**Comment by vaishali614** [comment]
@saumyasrivastava08 I think this doesn't look good. I would say try to design it same as the design shared above. Also, keep the button styling consistent with the whole website.

Screenshot (226)

PS: Don't forget to pull the latest changes.

CC: @DeepanshiD

**Comment by DeepanshiD** [comment]
@saumyasrivastava08  There are small changes that can be done to make it look better.
1. Opportunities drop down should come below "Post Opportunity" , This way it will look more in sync with opportunities visible.It must be left aligned.
2. The care of Opening, needs to have following details.
               - Logo of company 
               - Posting title
               - Company name
               - Date
               - Location
               - Deadline
               - Eligibility 
            To make this look elegant keep logo of company ( as it is right now ), adjacent to it add the Posting title, for eg: Frontend 
            Engineer, and below that the company name. The typography size for Posting title must be 3/4th or lesser than what it is 
            right now, and the company name should look smaller than posting title.
            Following this there will be another row, similar to current layout to keep Date, Location, Deadline, Eligibility
3. A background color for Post opening banner would do a great work, to add clear distinction, you can refer to https://colorhunt.co/ for matching color pallets and work on it.

**Comment by saumyasrivastava08** [comment]
> @saumyasrivastava08 There are small changes that can be done to make it look better.
> 
> 1. Opportunities drop down should come below "Post Opportunity" , This way it will look more in sync with opportunities visible.It must be left aligned.
> 2. The care of Opening, needs to have following details.
>    - Logo of company
>    - Posting title
>    - Company name
>    - Date
>    - Location
>    - Deadline
>    - Eligibility
>    To make this look elegant keep logo of company ( as it is right now ), adjacent to it add the Posting title, for eg: Frontend
>    Engineer, and below that the company name. The typography size for Posting title must be 3/4th or lesser than what it is
>    right now, and the company name should look smaller than posting title.
>    Following this there will be another row, similar to current layout to keep Date, Location, Deadline, Eligibility
> 3. A background color for Post opening banner would do a great work, to add clear distinction, you can refer to https://colorhunt.co/ for matching color pallets and work on it.

@DeepanshiD I need to make all these changes?

**Comment by DeepanshiD** [comment]
Yes, that will make it look decent.
It's a green flag from my side! 
It will be great to check with @Surajbokde @vaishali614

**Comment by saumyasrivastava08** [comment]
Screenshot (52)
@DeepanshiD is it okay

**Comment by DeepanshiD** [comment]
@saumyasrivastava08 Opportunity dropdown must come below the card for Post Opportunity.
And Post Opportunity card will look better with one color rather than two.

**Comment by saumyasrivastava08** [comment]
> @saumyasrivastava08 Opportunity dropdown must come below the card for Post Opportunity.
> And Post Opportunity card will look better with one color rather than two.

Below all the cards or below every single card?

**Comment by DeepanshiD** [comment]
@saumyasrivastava08 
Does this give a better idea?

WhatsApp Image 2021-03-11 at 14 09 29

**Comment by saumyasrivastava08** [comment]
> @saumyasrivastava08
> Does this give a better idea?
> 
> WhatsApp Image 2021-03-11 at 14 09 29

Screenshot (53)

**Comment by DeepanshiD** [comment]
@saumyasrivastava08 Great! Please keep one color in background of post opportunity banner.

**Comment by saumyasrivastava08** [comment]
> @saumyasrivastava08 Great! Please keep one color in background of post opportunity banner.

its one color rest is outline

**Comment by DeepanshiD** [comment]
@saumyasrivastava08 Then keep color of outline and box the same
And it will be done! :)

**Comment by saumyasrivastava08** [comment]
Screenshot (54)
@vaishali614 @DeepanshiD is it fine?

**Comment by vaishali614** [comment]
> > @saumyasrivastava08
> > Does this give a better idea?
> > WhatsApp Image 2021-03-11 at 14 09 29
> 
> Screenshot (53)

1. [Important] Please pull the latest changes from upstream and then make any changes.
2. The background color and buttons look totally out of sync from rest of the website.
3. Keep the background color as "#BD6997" and cover 100% width as in the screenshot (Rozgaar) I've shared before.
4. Keep the button styling exactly same as other buttons used in the website.
5. Increase the width of all Post Opportunity cards as in the screenshot(Rozgaar) I've shared before. Infact, the cards should be designed exactly same as in that screenshot.

CC: @Surajbokde @DeepanshiD

**Comment by saumyasrivastava08** [comment]
Screenshot (55)
@vaishali614

**Comment by DeepanshiD** [comment]
@saumyasrivastava08 
Remove icon which is above the button "Post Opportunity"
Keep the "Post Opportunity" button same as other buttons, i.e. Blue background White text.

**Comment by saumyasrivastava08** [comment]
@DeepanshiD done
@Surajbokde @abdus now merge it please.

**Comment by Surajbokde** [comment]
@saumyasrivastava08 please resolve conflict

**Comment by saumyasrivastava08** [comment]
> @saumyasrivastava08 please resolve conflict

How should I do that I tried it a lot

**Comment by saumyasrivastava08** [comment]
> > @saumyasrivastava08 please resolve conflict
> 
> How should I do that I tried it a lot

@Surajbokde Done now you can merge as a part of gssoc'2021.

**Comment by vaishali614** [comment]
> > > @saumyasrivastava08 please resolve conflict
> > 
> > 
> > How should I do that I tried it a lot
> 
> @Surajbokde Done now you can merge as a part of gssoc'2021.

@saumyasrivastava08 Your changes don't really look like what's required. Try to perfectly resolve all the changes listed below:

1. The background should cover the 100% width i.e. no extra spaces in left and right. 
2. The "Post Opportunity" button and the dropdown are not styled as we've in our homepage. The easiest way would be to copy the styling of "Explore" button from homepage.
3. Add heading for every View Opportunity page as Fulltime Jobs, Hackathons, Scholarships etc. (i.e. the headings mentioned in the cards on homepage) above "Post Opportunity" button.
4. Cards don't look good. Design it similar to the card in the screenshot attached below.

PS: Please refer the screenshot below and make the relevant changes. Also, update your PR only if you've made all these changes. 

Screenshot (224)

**Comment by saumyasrivastava08** [comment]
@vaishali614 merge this one for cards I will be doing next.

**Comment by saumyasrivastava08** [comment]
Screenshot (56)
I did the changes for the above 2 points 
for cards will create a new issue and will do there 
as the issue is #32 (to design mob view)

**Comment by Manvityagi** [comment]
@saumyasrivastava08 On the home page, these card images have been deleted.
image
Just add them again, and I will merge your PR.

**Comment by saumyasrivastava08** [comment]
> @saumyasrivastava08 On the home page, these card images have been deleted.
> image
> Just add them again, and I will merge your PR.

In my laptop it is showing

**Review by abdus — APPROVED** [review]

**Pull request merged**
