### PR TITLE
added-navbar

### LINKED ISSUE #218: Navbar in Sign in and Sign up page
### **Describe the bug:**

There should be navbar in each and every page but navbar is not present in sign in and sign up page

### PR DESCRIPTION
**Pull request by ritik307**
# Description

Added navbar to `login` and `signup` page

Fixed #218 

## Type of change

Please check options that are relevant to your PR.

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have pulled the latest changes in the repository
- [x] I have squashed my commits
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# Screenshots
navbar
navbar-login

### CODE REVIEW

**Comment by ritik307** [comment]
@vinitshahdeo plz review!

**Review by Manvityagi — CHANGES_REQUESTED** [review]
The card should remain in the center, it goes to left, leaving blank space on right side. 
Refer the gif attached, 
[](https://gifyu.com/image/tQ4S)

Please fix it. Rest looks good

**Comment by ritik307** [comment]
@Manvityagi sure!

**Comment by ritik307** [comment]
@Manvityagi Done! plz review

**Review by Manvityagi — APPROVED** [review]
Looks great!!

**Comment by ritik307** [comment]
@Manvityagi plz add the appropriate GSSOC label as by scorecard didn't update for this issue

**Pull request merged**
