### PR TITLE
Revamping of footer section as mentioned in issue-100

### LINKED ISSUE #100: Revamping the footer section
**Footer section** is vague as compare to other part of website. As a **GSSOC'21** participant I would like to work on this section.

image

### PR DESCRIPTION
**Pull request by Sakshi0401**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixed #100 

## Type of change

Please check options that are relevant to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ 1 ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [ 1 ] I have squashed my commits
- [ 1 ] My code follows the style guidelines of this project
- [ 1 ] I have performed a self-review of my own code
- [ 1 ] I have commented my code, particularly in hard-to-understand areas
- [ 1 ] I have made corresponding changes to the documentation
- [ 1 ] My changes generate no new warnings

### CODE REVIEW

**Comment by Surajbokde** [comment]
@Sakshi0401 please design footer for mobile and tab view

**Comment by Sakshi0401** [comment]
> @Sakshi0401 please design footer for mobile and tab view

@Surajbokde Okay I'll work on that.

**Comment by Sakshi0401** [comment]
> @Sakshi0401 please design footer for mobile and tab view

@Surajbokde Done with these changes. Please consider. #100

**Review by Surajbokde — APPROVED** [review]

**Comment by vaishali614** [comment]
@Sakshi0401 

1. Please pull the latest changes and update your PR.
2. Also, I see for some screen sizes, it's distorted. Please amend those.

Adding some screenshots for clarity:
1. The underline is extended long and copyright text is not center aligned
Capture

2. The image is too small
Capture2

3. Both 1 and 2 issues
Capture3

4. Same as 1
Capture4

CC: @DeepanshiD

**Comment by Sakshi0401** [comment]
okay thanks for reviewing .

**Comment by vaishali614** [comment]
> okay thanks for reviewing .

@Sakshi0401 Are you done with the changes?

**Comment by Sakshi0401** [comment]
> > okay thanks for reviewing .
> 
> @Sakshi0401 Are you done with the changes?

@vaishali614 Sorry for delay. I am almost done with it. I'll make PR by Tomorrow morning if it is okay !

**Comment by Sakshi0401** [comment]
@vaishali614 Made changes. Please consider.

**Comment by vaishali614** [comment]
> @vaishali614 Made changes. Please consider.

Looks good now. Before I merge, please pull the latest changes and update your PR.

**Comment by Sakshi0401** [comment]
> > @vaishali614 Made changes. Please consider.
> 
> Looks good now. Before I merge, please pull the latest changes and update your PR.

@vaishali614 Sorry but could you please guide me through it.

**Comment by vaishali614** [comment]
> > > @vaishali614 Made changes. Please consider.
> > 
> > 
> > Looks good now. Before I merge, please pull the latest changes and update your PR.
> 
> @vaishali614 Sorry but could you please guide me through it.

Please run the following commands to fetch latest changes from the remote repo:
`$ git fetch upstream`
`$ git merge upstream/develop`

**Comment by Sakshi0401** [comment]
> > > > @vaishali614 Made changes. Please consider.
> > > 
> > > 
> > > Looks good now. Before I merge, please pull the latest changes and update your PR.
> > 
> > 
> > @vaishali614 Sorry but could you please guide me through it.
> 
> Please run the following commands to fetch latest changes from the remote repo:
> `$ git fetch upstream`
> `$ git merge upstream/develop`

@vaishali614 Done with updating PR please review

**Comment by Sakshi0401** [comment]
@vaishali614 would you please add GSSOC'21 label to this PR. I haven't got any points for this PR because of absence of label.

**Pull request merged**
