### PR TITLE
Updated files for Post Opportunity 

### LINKED ISSUE #165: Post Opportunity Page Revamp
Revamping of Post Opportunity Page:

1. `Find Opportunity` button should redirect to `View Opportunity` page of respective opportunity.
2. Dropdown should have the following values which will redirect to `Post Opportunity` page of those opportunities: 
- JOB
- INTERNSHIP
- HACKATHON
- SCHOLARSHIP
- CODINGCOMPETITION
- CONFERENCE
3. `Find Opportunity` button in navbar should redirect to only that opportunity of which user is posting the opportunity.
4. Must be responsive for all screen sizes.

[Follow this design](https://www.figma.com/proto/XKmx5ia2hGjM9iz3VdWABp/girlcodeit?node-id=602%3A55&scaling=min-zoom&page-id=0%3A1)

### PR DESCRIPTION
**Pull request by Sukriti-sood**
# Description

- Made Chnages to Form UI of Post Opportunity according to the Design
- Added Find Opportunity Button in Navbar which will redirect  to View Opportunity page of respective opportunity
- UI is Responsive.

# Fixed #165

## Type of change

Please check options that are relevant to your PR.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have pulled the latest changes in the repository
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

Opportunity Cale (1)
Opportunity Cale (2)

### CODE REVIEW

**Review by vaishali614 — CHANGES_REQUESTED** [review]
@Sukriti-sood Amazing work. But, few changes are still required -
1. `Post Opportunity` button is not there. Please add that.
2. Female specific text isn't in the right font-style, font-size and font-weight.
3. Female specific toggle should be next to the description.
4. Labels shouldn't be italic.
5. Heading should be properly aligned with the form fields.
6. There shouldn't be any space between the form background and footer.
7. Do check if you can modify the toggle as per the design (not a priority)

**Comment by Sukriti-sood** [comment]
- [x] Female specific text isn't in the right font-style, font-size and font-weight.
- [x] Female specific toggle should be next to the description.
- [x] Labels shouldn't be italic.
- [x] Heading should be properly aligned with the form fields.
- [x] There shouldn't be any space between the form background and footer.
screencapture-localhost-3000-postopportunity-fulltime-2021-05-22-08_53_21


@vaishali614  I didn't get about which Post Opportunity Button you are mentioning

**Comment by vaishali614** [comment]
> * [x]  Female specific text isn't in the right font-style, font-size and font-weight.
> * [x]  Female specific toggle should be next to the description.
> * [x]  Labels shouldn't be italic.
> * [x]  Heading should be properly aligned with the form fields.
> * [x]  There shouldn't be any space between the form background and footer.
>   screencapture-localhost-3000-postopportunity-fulltime-2021-05-22-08_53_21
> 
> @vaishali614 I didn't get about which Post Opportunity Button you are mentioning

1. It wasn't visible earlier, but it's there now. Just align it along the form fields. And keep the border radius similar to the one in navbar.
2. Labels shouldn't be bold. Keep the font-weight same as in the design.
3. Female specific toggle button should be aligned with the bottom of description, not the top of it.

Rest everything seems fine.

Also, the deploy-preview seems distorted. Maybe that's because of the merge conflicts, please resolve it and test the deploy-preview completely before updating your PR.

**Comment by Sukriti-sood** [comment]
@vaishali614  I didn't change the position of Toggle because at bottom , it doesn't' looks good
Opportunity Cale (3)
Opportunity Cale (4)

**Comment by vaishali614** [comment]
@Sukriti-sood Yeah you're right. Let the toggle button be next to website field then.

Also, a recent PR has been merged which combines all these forms into one. You'll have to get rid of merge conflicts now. Please do that carefully. Make sure you don't destroy your changes.

**Comment by Sukriti-sood** [comment]
> @Sukriti-sood Yeah you're right. Let the toggle button be next to website field then.
> 
> Also, a recent PR has been merged which combines all these forms into one. You'll have to get rid of merge conflicts now. Please do that carefully. Make sure you don't destroy your changes.

@vaishali614  Done , If you also think Please make this PR level3 ,

**Review by vaishali614 — APPROVED** [review]

**Pull request merged**
