### PR TITLE
ADDED dark mode

### LINKED ISSUE #38: Adding Dark mode to the site.
I want to add a button that will toggle between Dark and Light mode.

### PR DESCRIPTION
**Pull request by mohammedjameel24**
# Description

Added darkmode theme to the website 

Fixed # (issue) (e.g. Fixed #8)
Fixed #38 

## changes

Please check options that are relevant to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have pulled the latest changes in the repository
- [x] I have squashed my commits
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by mohammedjameel24** [comment]
please merge @vaishali614

**Comment by vaishali614** [comment]
> please merge @vaishali614

1. When we switch to dark mode, the black texts should turn white and blue should remain blue.
2. Navbar background should also turn black and text color should turn white.

**Review by Manvityagi — CHANGES_REQUESTED** [review]
There are some points mentioned by @vaishali614 in a comment, Please do those changes, and additionally, the button to toggle between dark and normal mode can also be improved, I think.
@DeepanshiD Can you suggest something for the toggle button after looking at the preview.

**Comment by mohammedjameel24** [comment]
now ? @vaishali614  @Manvityagi @DeepanshiD

**Review by vaishali614 — CHANGES_REQUESTED** [review]
@mohammedjameel24 I don't see any of the requested changes implemented. Instead, you've decreased the size of banner gif. Please undo that and make the changes as requested.

**Comment by mohammedjameel24** [comment]
i can see changes locally but not in deploy preview ?
attaching proof 
image

**Comment by vaishali614** [comment]
> i can see changes locally but not in deploy preview ?
> attaching proof
> image

@Manvityagi @abdus Can anyone of you please help him with this?

**Review by Siddhant-K-code — CHANGES_REQUESTED** [review]
Good Work @mohammedjameel24

But There are some minor bugs with this. 

initially when it is loading, Dark Mode Toggle Button is showing at left:

image


**But**,

When Page Gets Loaded Successfully, it comes to the right side: 

image

Also, it is coming over the "To the Top" Button:

image

**Comment by vaishali614** [comment]
I agree with @Siddhant-K-code. @mohammedjameel24 please take care of these issues and update your PR soon with all the mentioned changes.

**Comment by Manvityagi** [comment]
> I agree with @Siddhant-K-code. @mohammedjameel24 please take care of these issues and update your PR soon with all the mentioned changes.

Are you updating this @mohammedjameel24 or Shall I close it and open the issue for others to take?

**Comment by vaishali614** [comment]
@mohammedjameel24 Due to your inactiveness, I'm closing this PR.

**Pull request closed without merging**
