### PR TITLE
Link to opportunities added in navbar

### LINKED ISSUE #151: Update What we Do? field in NavBar
In the Navbar Replace `What we do?` with `Opportunities` and link it to `Know About Section`. 

Refer the image for more clarity:
image

### PR DESCRIPTION
**Pull request by akshitakanojia**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixed #151 

## Type of change

Please check options that are relevant to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have pulled the latest changes in the repository
- [ ] I have squashed my commits
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by vaishali614** [comment]
@akshitakanojia You haven't taken the latest pull. Please mark the checklist correctly.
Please pull the latest changes and update your PR to get it merged.

**Comment by akshitakanojia** [comment]
I tried updating the branch but it says everything is up-to-date.

Update: I found that my issue branch is lagging behind for some reason but develop is fine. So should I make a new branch from the updated develop branch and make a new PR as I could not find a way to pull changes in this issue branch?

**Comment by Manvityagi** [comment]
> I tried updating the branch but it says everything is up-to-date.
> 
> Update: I found that my issue branch is lagging behind for some reason but develop is fine. So should I make a new branch from the updated develop branch and make a new PR as I could not find a way to pull changes in this issue branch?

This is how changes from one branch are pulled into another. 

On your local branch
git stash

git checkout develop 
git fetch upstream 
git merge upstream/develop 

git checkout your-branch 

git rebase develop 
git stash apply 

After running these commands in the order above, you will be good to go @akshitakanojia.
If you still face any problems, feel free to ping again.

**Comment by akshitakanojia** [comment]
@Manvityagi after the above process I am not able to push the changes it's showing error. Do I need to force push?

**Comment by Manvityagi** [comment]
> @Manvityagi after the above process I am not able to push the changes it's showing error. Do I need to force push?

`git push -u origin YOUR_BRANCH` should have worked fine. What's the error you getting? 
Ping me on discord @mt2107#5952

**Comment by vaishali614** [comment]
@akshitakanojia is your problem solved? if not, please ping anyone of us on discord and get it resolved so that we can merge this PR.

**Review by Manvityagi — APPROVED** [review]

**Pull request merged**
