### PR TITLE
Added the code file for DARK MODE

### LINKED ISSUE #38: Adding Dark mode to the site.
I want to add a button that will toggle between Dark and Light mode.

### PR DESCRIPTION
**Pull request by 0Faiz0**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixed #38  (issue) (e.g. Fixed #8)

## Type of change

Please check options that are relevant to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [*] This change requires a documentation update

# Checklist:

- [ ] I have squashed my commits
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by Manvityagi** [comment]
Where exactly is the option to switch to Dark Mode in the website? @0Faiz0

**Comment by abdus** [comment]
how can I enable dark mode?

**Comment by 0Faiz0** [comment]
> Where exactly is the option to switch to Dark Mode in the website? @0Faiz0

I did a mistake... I thought i have to share the code and not to implement in the website .... I'm sorry.... I'm new to this

**Comment by Manvityagi** [comment]
> > Where exactly is the option to switch to Dark Mode in the website? @0Faiz0
> 
> I did a mistake... I thought i have to share the code and not to implement in the website .... I'm sorry.... I'm new to this

No issues, make changes to your code, and commit again.

**Comment by Manvityagi** [comment]
> > > Where exactly is the option to switch to Dark Mode in the website? @0Faiz0
> > 
> > 
> > I did a mistake... I thought i have to share the code and not to implement in the website .... I'm sorry.... I'm new to this
> 
> No issues, make changes to your code, and commit again.

@0Faiz0 Because of inactivity, I am closing this PR and making this issue available to others for grabbing.

**Pull request closed without merging**
