### PR TITLE
Add Same Style to all the Buttons

### LINKED ISSUE #125: Change styling of all buttons
All buttons on the website should have the same styling as that of "Explore" button on homepage.

### PR DESCRIPTION
**Pull request by leoshrey**
# Description

This changes the styling of all the Buttons on Opportunity Calendar website. 
Now all the buttons follows the same style as "Explore" Button.
Design consistency is maintained for a better User Experience.

Fixes #125 

## Type of change

Please check options that are relevant to your PR.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have squashed my commits
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by Surajbokde — APPROVED** [review]
checked via command line instruction

**Comment by leoshrey** [comment]
What I think is, We have to add **"import React, { Component }  from 'react';"** in _Hackathons.js_ file which could have been accidently removed by someone and project is not able to build with netlify. As it is throwing an error on _Hackathons.js_ file as mentioned in the error logs. 
Do you want me to do the changes and then commit again or It will be okay with the normal execution after this will be merged ?

**Comment by abdus** [comment]
@leoshrey yeah just make the changes and push again. should pass the checks

**Comment by leoshrey** [comment]
@abdus, I need a suggestion. 
Do I need to undo the last pushed commit changes and then after adding the latest change I have to stage them all and then push again forming the new commit 
**OR** 
I just have to add the latest changes and push the new commit without any undoing or reverting back?

**Comment by abdus** [comment]
No. you won't have to do anything like reverting and all. just open that file where the import missing. and add `import React from 'react'` at the top. and then commit and push changes to your branch.

**Review by Surajbokde — APPROVED** [review]

**Review by vaishali614 — APPROVED** [review]

**Pull request merged**
