### PR TITLE
Added animation to about cards

### LINKED ISSUE #29: [ Enhacement ] Add animation in cards of known about
image

1. add animation in cards-

animation maybe related to cards hover , change of image ,etc

2. modify the card.

add proper screenshots of your work

### PR DESCRIPTION
**Pull request by vismitap**
Fixed #29

# Description
The changes made are:
* Fixed 2 problems in `KnowAboutCard.module.css`.
* Added animation for the cards.
* Change the title in `index.html` from 'React App' to 'Girl Code It'.
* 
Fixed #29 

## Type of change

Please check options that are relevant to your PR.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have squashed my commits
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings.

## Video Demonstration
Please refer [this video](https://i.imgur.com/UDy7SR9.mp4)

### CODE REVIEW

**Comment by Manvityagi** [comment]
This branch has conflicts that must be resolved. @vismitap

**Comment by Manvityagi** [comment]
This branch has conflicts that must be resolved @vismitap

**Comment by vismitap** [comment]
> This branch has conflicts that must be resolved @vismitap

Yes will resolve it👍

**Review by Manvityagi — APPROVED** [review]
I am approving it, waiting for @Surajbokde to approve.

**Review by Surajbokde — APPROVED** [review]
Approve as level1 tag

**Comment by Manvityagi** [comment]
Also, make sure from next time, the branch name should be `feature-branch` @vismitap. 

Merging this one, Congratulations on your first merge 🎉 
Glad to have your contributions :)

**Comment by vismitap** [comment]
> Also, make sure from next time, the branch name should be `feature-branch` @vismitap.
> 
> Merging this one, Congratulations on your first merge 🎉
> Glad to have your contributions :)

Yeah! Thanks! will keep that in mind for next PRs! ✌🤩

**Pull request merged**
