### PR TITLE
View Opportunity Page Revamp

### LINKED ISSUE #164: View Opportunity Page Revamp
Revamping of View Opportunity Page:

1. `Post Opportunity` button should redirect to `Post Opportunity` page of respective opportunity.
2. `Select Opportunity` dropdown should have: 
- Fulltime Jobs
- Hackathons
- Scholarships
- Coding Competitions
- Tech Conferences
- Internships
3. The banner heading should change accordingly.
4. Must be responsive for all screen sizes.

[Follow this design](https://www.figma.com/proto/XKmx5ia2hGjM9iz3VdWABp/girlcodeit?node-id=11%3A62&scaling=min-zoom&page-id=0%3A1)

### PR DESCRIPTION
**Pull request by MennaMagdy2019**
# Description
1-I made a Post Opportunity button that redirects to the Post Opportunity page of the respective opportunity.
2-I made Select Opportunity dropdown and the banner heading change accordingly
3-  made the page responsive for all screen sizes

Fixed #164

## Type of change
in the navbar, I made a button,
 in the page Select Opportunity dropdown and
in the file in CSS that to make changes and responsive for screen

Please check options that are relevant to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have pulled the latest changes in the repository
- [x] I have squashed my commits
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by MennaMagdy2019** [comment]
Can you review my issue? @vaishali614

**Comment by vaishali614** [comment]
> Can you review my issue? @vaishali614

Your changes don't follow the design shared in the issue. Please try to replicate the same. By replicating the same, I mean same color scheme, same font-size, same padding/margin etc. for all the categories (Fulltime, Internships, Scholarships etc.)

**Comment by MennaMagdy2019** [comment]
I tried to make my changes follow the design shared in the issue, 
can you review it again and tell me the difference between them?
thanks, @vaishali614

**Comment by vaishali614** [comment]
> I tried to make my changes follow the design shared in the issue,
> can you review it again and tell me the difference between them?
> thanks, @vaishali614

1. Search Bar:
- It should be an input field
- Darker shade of background
- Search icon looks weird
- Font size doesn't match

2. Post Opportunity button and Login/Signup button don't follow the same styling.

3. Search bar, Post Opportunity button, Login/Signup button are not aligned.

4. Select Opportunity Dropdown:
- Darker shade of background
- Height and width don't match

5. Opportunity Cards:
- There's no blue header in design
- Card details given in design are just for example. You have to display the data fetched from API.
- Date, Location icons don't match
- `Know More` and `Apply` buttons don't follow the same styling
- Cards are not in middle of the page

These are some clear differences from the design. Please try to fix these.

Note: Please take the latest pull from upstream.

**Comment by vaishali614** [comment]
@MennaMagdy2019 This was a Level 2 issue for which 5 days are assigned. If you don't respond by tonight, I'll have to assign the issue to someone else.

**Comment by vaishali614** [comment]
@MennaMagdy2019 Due to your inactiveness, I'm closing this PR.

**Pull request closed without merging**
