### PR TITLE
google signin implemented

### LINKED ISSUE #158: want to implement google Google SignIn
### **Feature request**:
want to implement google sign in

your code ->

Screenshot 2021-03-27 at 2 13 10 PM

### **Describe the solution you'd like**:

my solution -> 

Screenshot 2021-03-27 at 5 08 25 PM

Screenshot 2021-03-27 at 5 08 37 PM

Screenshot 2021-03-27 at 5 08 54 PM

Screenshot 2021-03-27 at 2 23 44 PM

### PR DESCRIPTION
**Pull request by abhay27chauhan**
# Description

implemented google signin

Fixed #158 

## Type of change

Please check options that are relevant to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have pulled the latest changes in the repository
- [x] I have squashed my commits
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by abhay27chauhan** [comment]
@abdus kindly review my PR

**Comment by ay2306** [comment]
I think we should go with this strategy
1. Redirect to `{backend-url}/auth/google-authenticate`, from the front-end and login/register logic is handled at the server
2. Generate a JWT for the user UUID and pass it to the front-end using path query.

The reason I suggest this:
1. Client Secrets will be better secure at the backend
2. Single Route accepting JWT for any login/register strategy will make it simple for the front-end while logic for all those still needs to be maintained at the backend.

Please see this issue and verify the strategy: [Backend Issue 33](https://github.com/Girl-Code-It/Opportunity-Calendar-Backend/issues/33)

**Comment by abhay27chauhan** [comment]
> I think we should go with this strategy
> 
> 1. Redirect to `{backend-url}/auth/google-authenticate`, from the front-end and login/register logic is handled at the server
> 2. Generate a JWT for the user UUID and pass it to the front-end using path query.
> 
> The reason I suggest this:
> 
> 1. Client Secrets will be better secure at the backend
> 2. Single Route accepting JWT for any login/register strategy will make it simple for the front-end while logic for all those still needs to be maintained at the backend.
> 
> Please see this issue and verify the strategy: [Backend Issue 33](https://github.com/Girl-Code-It/Opportunity-Calendar-Backend/issues/33)

bro if want to handle the google singin on backend, we won't be using react-google-login instead we will be using passport

**Comment by abhay27chauhan** [comment]
pls read this -
https://www.npmjs.com/package/react-google-login
shows how it is implemented

> I think we should go with this strategy
> 
> 1. Redirect to `{backend-url}/auth/google-authenticate`, from the front-end and login/register logic is handled at the server
> 2. Generate a JWT for the user UUID and pass it to the front-end using path query.
> 
> The reason I suggest this:
> 
> 1. Client Secrets will be better secure at the backend
> 2. Single Route accepting JWT for any login/register strategy will make it simple for the front-end while logic for all those still needs to be maintained at the backend.
> 
> Please see this issue and verify the strategy: [Backend Issue 33](https://github.com/Girl-Code-It/Opportunity-Calendar-Backend/issues/33)

**Comment by abhay27chauhan** [comment]
> I think we should go with this strategy
> 
> 1. Redirect to `{backend-url}/auth/google-authenticate`, from the front-end and login/register logic is handled at the server
> 2. Generate a JWT for the user UUID and pass it to the front-end using path query.
> 
> The reason I suggest this:
> 
> 1. Client Secrets will be better secure at the backend
> 2. Single Route accepting JWT for any login/register strategy will make it simple for the front-end while logic for all those still needs to be maintained at the backend.
> 
> Please see this issue and verify the strategy: [Backend Issue 33](https://github.com/Girl-Code-It/Opportunity-Calendar-Backend/issues/33)

pls read this -
https://www.npmjs.com/package/react-google-login
shows how it is implemented

**Comment by ay2306** [comment]
@abhay27chauhan Yes, I was working on the Google Login/Register on the backend that's why I proposed the strategy. This is not my PR.

**Comment by ay2306** [comment]
@abhay27chauhan Yes, I was proposing exactly that. To implement login/register strategies on the backend.

**Comment by abhay27chauhan** [comment]
> @abhay27chauhan Yes, I was proposing exactly that. To implement login/register strategies on the backend.

i haven't written any logic. react google login is a component, i have just provided clientid as a prop

**Comment by abhay27chauhan** [comment]
after authenticating it returns a profile object

**Comment by abhay27chauhan** [comment]
it is created to handle login/register on frontend without writing so much code in case of passport

**Comment by abhay27chauhan** [comment]
and i don't think to store this profile object on to the database even. It can be store in the local storage. And when we want to logout we can remove the data from the local storage.
Because generally users only login to google from their own PC so saving it on local storage is easy and quick.

**Comment by abhay27chauhan** [comment]
> and i don't think there is any need to store this profile object on to the database even. It can be store in the local storage. And when we want to logout we can remove the data from the local storage.
Because generally users only login to google from their own PC so saving it on local storage is easy and quick.

**Comment by ay2306** [comment]
> and i don't think to store this profile object on to the database even. It can be store in the local storage. And when we want to logout we can remove the data from the local storage.
> Because generally users only login to google from their own PC so saving it on local storage is easy and quick.

Why login for just front-end? Login gives some privileges to the user. Can you explain what will be the benefit of logging in and not using data on the backend? If we using this data to authenticate for some requests, then anyway we will have to create a user profile in the database. What is the long-term or short-term goal of keeping it on the front-end?

**Comment by abhay27chauhan** [comment]
you can send the profile data to backend, if you want to use that data. I am not saying you can't

**Comment by ay2306** [comment]
@abhay27chauhan Yes we can do that but doing it does not make sense. Reason to implement it on the backend
1. Just pass a JWT to the backend instead of a complete profile every time making a request to authorize or authenticate.
2. Secrets are better stored on the server than serving web pages with Google API secrets
3. Front end can simply use the abstract authentication feature from the backend
4. User can just change the data in the front end (not sure much about this but a hack worth trying) when sending user data along with the request. 
5. Crazy sync up between the front end and backend will be required for every strategy introduced on the front end.

**Comment by abhay27chauhan** [comment]
@ay2306 do you know reactjs?

**Comment by abhay27chauhan** [comment]
@ay2306 ok explain me how you do it using react google login library. Or you don't want to use it. How you want to implement google sign in

**Comment by ay2306** [comment]
@abhay27chauhan I am saying not to implement on front end. Rather redirect to `backend-url/auth/google-authenticate`, it serves google service for Login, then backend redirect it to `frontend-url/login?token=<token>`, front end stores the token and requests data using token.

**Comment by abhay27chauhan** [comment]
@ay2306 can you show me how are you planning to do it? Code snippet?

**Comment by abhay27chauhan** [comment]
So that I can get a clear idea

**Comment by ay2306** [comment]
I am not talking about if we can implement it or not. I am discussing about the software design here. It is not recommended to have secrets on publicly available resources and there are various other security and implementation benefits that I have already mentioned in the thread by taking this feature to the backend.

PS: please reply in one comment only.

**Comment by abhay27chauhan** [comment]
@ay2306 I want to know from where in frontend you want to make request to backend

**Comment by Manvityagi** [comment]
> @abhay27chauhan Yes we can do that but doing it does not make sense. Reason to implement it on the backend
> 
> 1. Just pass a JWT to the backend instead of a complete profile every time making a request to authorize or authenticate.
> 2. Secrets are better stored on the server than serving web pages with Google API secrets
> 3. Front end can simply use the abstract authentication feature from the backend
> 4. User can just change the data in the front end (not sure much about this but a hack worth trying) when sending user data along with the request.
> 5. Crazy sync up between the front end and backend will be required for every strategy introduced on the front end.

This seems convincing to me @ay2306. 
CC: @abdus

**Comment by abhay27chauhan** [comment]
> > @abhay27chauhan Yes we can do that but doing it does not make sense. Reason to implement it on the backend
> > 
> > 1. Just pass a JWT to the backend instead of a complete profile every time making a request to authorize or authenticate.
> > 2. Secrets are better stored on the server than serving web pages with Google API secrets
> > 3. Front end can simply use the abstract authentication feature from the backend
> > 4. User can just change the data in the front end (not sure much about this but a hack worth trying) when sending user data along with the request.
> > 5. Crazy sync up between the front end and backend will be required for every strategy introduced on the front end.
> 
> This seems convincing to me @ay2306.
> CC: @abdus

@abdus can somebody explain why u need to authenticate on backend when 'react google login' component is doing it in just one single line. You just need need to store that object and later used to store and retrieve the user data.
If you want to implement the authentication part on to the backend then why have to used 'react google login' in the first place. 
And secondly, which client secrets are you talking about. There is no client secret.
The object returned after authentication has 4 fields
1. family name
2. given name
3. googleId
4. image url

**Comment by abhay27chauhan** [comment]
@manvi ' react google login ' component is an abstraction which handle all the important logic for you, and returns you a simple object which can be store in database and later can be used to retrieve or store the user data. All the heavy and long work is done by them, so nothing is in open. The component is created to make things simple and easy for developers.

**Comment by abhay27chauhan** [comment]
and since you are talking about client secrets on frontend is not good practice(which is not in this case). 
If you have ever used firebase the client secrets for processing payments are handled on frontend. So, there is nothing like that it is not good, it just what is more easy and fast.

**Comment by abdus** [comment]
@abhay27chauhan front-end for Opportunity-Calender talks to backend via an API. So, I think @ay2306 is right here. We should just fall back to using JSONWebToken for the auth mechanism. 

Here's how it will work(@ay2306, please correct me if I am wrong): 
1. user clicks on 'Login with Google' button 
2. page is redirected to the google auth handler page. 
3. Google responds with the access token, refresh token and all other personal information
4. client sends these data to backend. 
5. tokens are stored on the back-end (to keep it simple, let's not discuss how backend people would handle it) and responds with a JWT.
6. now that client has a jwt, it can carry on further requests which require auth

---

@abhay27chauhan I went through the changes you have made. I don't mean to demotivate you, but it hardly adds any value to the existing codebase. to sum up all the changes: 

1. you added two functions, error callback and success callback, both just logs the response of Google. you added a placeholder for 
2. there is a placeholder for `clientId`. we eventually have to change it to a real value. 

Let me tell you why I think these changes do not add much value. `react-google-login` abstracts most of the things for us. It takes care of setting up 'Login with Google' along with error and success handlers. And it is a [well tested](https://github.com/anthonyjgrove/react-google-login/tree/master/__test__) library.

---

I am going to close this pull request because of the above-mentioned reasons. Please don't hesitate to reopen it if you think I am wrong. I will be happy to merge it. Have a good day.

**Comment by abhay27chauhan** [comment]
> @abhay27chauhan front-end for Opportunity-Calender talks to backend via an API. So, I think @ay2306 is right here. We should just fall back to using JSONWebToken for the auth mechanism.
> 
> Here's how it will work(@ay2306, please correct me if I am wrong):
> 
> 1. user clicks on 'Login with Google' button
> 2. page is redirected to the google auth handler page.
> 3. Google responds with the access token, refresh token and all other personal information
> 4. client sends these data to backend.
> 5. tokens are stored on the back-end (to keep it simple, let's not discuss how backend people would handle it) and responds with a JWT.
> 6. now that client has a jwt, it can carry on further requests which require auth
> 
> @abhay27chauhan I went through the changes you have made. I don't mean to demotivate you, but it hardly adds any value to the existing codebase. to sum up all the changes:
> 
> 1. you added two functions, error callback and success callback, both just logs the response of Google. you added a placeholder for
> 2. there is a placeholder for `clientId`. we eventually have to change it to a real value.
> 
> Let me tell you why I think these changes do not add much value. `react-google-login` abstracts most of the things for us. It takes care of setting up 'Login with Google' along with error and success handlers. And it is a [well tested](https://github.com/anthonyjgrove/react-google-login/tree/master/__test__) library.
> 
> I am going to close this pull request because of the above-mentioned reasons. Please don't hesitate to reopen it if you think I am wrong. I will be happy to merge it. Have a good day.

@abdus I have done alot more if you have implemented redux or react context api because without that i can't do anything with the generated data. That's why i have asked for it in the starting.
I am saying the same thing from starting that you have send this generated data and store it for further use (what ever you do on backend).

**Comment by abdus** [comment]
@abhay27chauhan I think I mentioned on Discord chat that you can use context API.

**Comment by ay2306** [comment]
@abdus Yes, I will create the issue for front end jwt accepting route and will share redirect backend url in the issue as well once google auth issue is completed on the backend.

**Pull request closed without merging**
