### PR TITLE
Remaking of signIn/signUp pages

### PR DESCRIPTION
**Pull request by kumarishalini6**
#fixes(issue-126)
I have added images and improve forms .
 
Opportunity Calendar - Personal - Microsoft​ Edge 5_2_2021 07_07_58 PM
Opportunity Calendar - Personal - Microsoft​ Edge 5_2_2021 07_07_33 PM
Opportunity Calendar - Personal - Microsoft​ Edge 5_2_2021 07_07_48 PM
Opportunity Calendar - Personal - Microsoft​ Edge 5_2_2021 07_08_11 PM

### CODE REVIEW

**Comment by vaishali614** [comment]
@kumarishalini6 

1. Please take the latest pull from upstream
2. There's a lot of space above the form, but there's no space between form and footer. The form should have same space on both ends.
3. Add same amount of padding above heading 'Sign up' / 'Login' as much you had added above 'Forgot Password' 
4. Remove the label for Confirm Password in Sign up form.

Rest of the things seem fine.

**Comment by kumarishalini6** [comment]
can you explain 3rd point.

**Comment by vaishali614** [comment]
> can you explain 3rd point.

It's twice. Remove the one in the end.
Capture

**Comment by kumarishalini6** [comment]
3rd point in which you are talking about padding

**Comment by vaishali614** [comment]
> 3rd point in which you are talking about padding

The space above Forgot Password is more than the space above Sign up inside the form.
Please try to implement same padding, margin etc. as you have added for Forgot Password form.

Screenshot (60)

Screenshot (59)

**Comment by kumarishalini6** [comment]
check it please
Opportunity Calendar - Personal - Microsoft​ Edge 5_8_2021 06_20_56 PM
Opportunity Calendar - Personal - Microsoft​ Edge 5_8_2021 06_21_12 PM
Opportunity Calendar - Personal - Microsoft​ Edge 5_8_2021 06_27_07 PM
Opportunity Calendar - Personal - Microsoft​ Edge 5_8_2021 06_29_12 PM

**Comment by kumarishalini6** [comment]
Wait I have made some  more changes

**Comment by kumarishalini6** [comment]
Opportunity Calendar - Personal - Microsoft​ Edge 5_8_2021 06_37_05 PM
Opportunity Calendar - Personal - Microsoft​ Edge 5_8_2021 06_37_14 PM
Opportunity Calendar - Personal - Microsoft​ Edge 5_8_2021 06_37_23 PM
Opportunity Calendar - Personal - Microsoft​ Edge 5_8_2021 06_37_31 PM

Now check all changes that you have told are made

**Comment by kumarishalini6** [comment]
Hey! I want to know from where you picked the animated images that you have put in home page 
Can you share the website name please

**Comment by vaishali614** [comment]
> Hey! I want to know from where you picked the animated images that you have put in home page
> Can you share the website name please

I'm not really sure about the website. It was done by some contributor.

**Comment by vaishali614** [comment]
@kumarishalini6 Seems good to me now, but please take the latest pull from upstream to get this PR merged.

**Comment by kumarishalini6** [comment]
ok

**Comment by kumarishalini6** [comment]
Done

**Pull request merged**
