### PR TITLE
Search icon added

### LINKED ISSUE #234: add search icon
### **Feature request**:

I want to add search icon in the search bar.

Please assign this issue to me.
### **Additional context:**

<hr/>

**Note:**

- If you want to work on an issue, you should check if it has already been assigned to anyone.

### PR DESCRIPTION
**Pull request by ShrutiOmer**
# Description

I have added search Icon to the search option.

Fixed #234 (e.g. Fixed #8)

## Type of change

Please check options that are relevant to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have pulled the latest changes in the repository
- [ ] I have squashed my commits
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

image

### CODE REVIEW

**Review by Manvityagi — CHANGES_REQUESTED** [review]
The position of search icon doesn't seem to be in sync with 'Search text`

**Comment by ShrutiOmer** [comment]
@Manvityagi  Is it now looking fine?
image

**Comment by Manvityagi** [comment]
> @Manvityagi Is it now looking fine?
> image

The shape of search input was fine, 
I meant the search icon doesn't seem to be aligned with Placeholder 'Search'

**Comment by ShrutiOmer** [comment]
image

@Manvityagi Does it works?

**Comment by Manvityagi** [comment]
> image
> 
> @Manvityagi Does it works?

Not really 🧐 
Reverse it to the first thing that you did, 
That looks the best among all these

**Comment by ShrutiOmer** [comment]
@Manvityagi  Ok, Actually I did not commit any changes to the Pull request, the files are same.
image

**Review by vaishali614 — APPROVED** [review]

**Pull request merged**
