### PR TITLE
feedback form

### PR DESCRIPTION
**Pull request by kumarishalini6**
#255

InkedOpportunity Calendar - Personal - Microsoft​ Edge 5_18_2021 01_00_45 PM_LI

https://user-images.githubusercontent.com/69043944/118611411-47dc4880-b769-11eb-841b-f2f67ae6d2f0.mp4

### CODE REVIEW

**Comment by kumarishalini6** [comment]
Please review this PR the GSSoC'21 about to end.

**Comment by vaishali614** [comment]
@DeepanshiD @Manvityagi Please suggest a better place for Feedback button. I don't like it in the navbar.

**Comment by DeepanshiD** [comment]
We can keep it parallel to the selected opportunity dropdown on the right hand side.
CC: @vaishali614 @Manvityagi

**Review by vaishali614 — CHANGES_REQUESTED** [review]
@DeepanshiD Yeah that would be better.

@kumarishalini6 Few changes are required:
1. Shift the `Feedback` button to the right side parallel to the opportunity dropdown. Make sure the padding is same on both sides.
2. The button should have same border-radius as the `Login` button.
3. The form should open in new tab. (Use target=_blank in anchor tag)

**Comment by kumarishalini6** [comment]
I have made changes please review it . 
Opportunity Calendar - Personal - Microsoft​ Edge 5_20_2021 09_38_09 PM

**Review by Surajbokde — CHANGES_REQUESTED** [review]
@kumarishalini6 
image
remove this feedback button add add the feedback link in footer(links column)
image

here

**Comment by kumarishalini6** [comment]
ok

**Comment by kumarishalini6** [comment]
Done

**Review by Surajbokde — APPROVED** [review]

**Review by vaishali614 — APPROVED** [review]

**Pull request merged**
