### PR TITLE
feat: Arrangement of Buttons in HomePage #205

### LINKED ISSUE #205: Arrangement of Buttons in HomePage
- [x] I checked to make sure that this issue has not already been filed.

- [x] I'm reporting the issue to the correct repository (for multi-repository projects) **(optional)**

# Expected Behavior:

Please describe the behavior you are expecting.
The Explore button should be moved to its left, Know More button should be moved up and aligned with the blue line above it right now.

# Current Behavior:

What is the current behavior?
The Explore Button is placed on the right-hand side which leaves so much unwanted space.
The Know More button is placed below the Blue line which is visually displeasing. 

# Solution:

Please describe what will you do to solve this issue or your approach to solve this issue.
I'll move the Explore button to the left side and make sure it's aligned with the text. The Know more button will be brought slightly up so that it aligns with the blue line giving a better visual appearance

# Screenshots (optional):
image
image

### PR DESCRIPTION
**Pull request by anhushree**
# Description

The alignment of the Know more button was shifted to the top and left. It is responsive in all sizes.

Fixed #205  

## Type of change

Please check options that are relevant to your PR.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have pulled the latest changes in the repository
- [x] I have squashed my commits
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by vaishali614 — CHANGES_REQUESTED** [review]
The button should be more close to the About Us content. There should be enough space between the button and next heading.

Capture

**Comment by anhushree** [comment]
Kindly check, I have made the respective changes.

**Comment by anhushree** [comment]
@vaishali614 Kindly check and let me know if anything else is to be done.

**Review by vaishali614 — APPROVED** [review]

**Comment by vaishali614** [comment]
@anhushree Changes look good. Please take the latest pull and update your PR to get it merged.

**Pull request merged**
